require("util")
require("defines")
require("datalib")
require("prototypes.loop.item")
require("prototypes.loop.projectiles")

require("prototypes.entity")
require("prototypes.accumulator_entity")
require("prototypes.walls_entity")
require("prototypes.gates_entity")
require("prototypes.item.gun")
require("prototypes.item.ammo")
require("prototypes.categories")
require("prototypes.recipe")
require("prototypes.technology")