require("util")
require("defines")
require("data_paths")
require("data_lib")
require("prototypes.loop.item")
require("prototypes.loop.projectiles")

require("prototypes.entity")
require("prototypes.entity_vehicle")
require("prototypes.entity_energy")
require("prototypes.entity_defense")
require("prototypes.item_vehicle")
require("prototypes.item.gun")
require("prototypes.item.ammo")
require("prototypes.categories")
require("prototypes.recipe")
require("prototypes.technology")